# This is a basic workflow to help you get started with Actions

name: Build Docker container

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  base:
    name: Base container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [6.1, 6.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout toolkit repository
      uses: actions/checkout@v2
      with:
        repository: SynologyOpenSource/pkgscripts-ng
        ref: master
        path: pkgscripts-ng

#    - name: Modify toolkit scripts
#      run: |
#        sed -i 's/title = "Link Project"/title = "Copy Project"/g' pkgscripts-ng/PkgCreate.py
#        sed -i 's/print("Link %s -> %s"/print("Copy %s -> %s"/g' pkgscripts-ng/include/python/link_project.py
#        sed -i 's/-al/-a/g' pkgscripts-ng/include/python/link_project.py

    - name: Login to DockerHub
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Build Base container
      run: docker build --file Dockerfile.base --build-arg DSM_VERSION=${{ matrix.version }} -t cwuensch/synobuild:base_${{ matrix.version }} .
      
#    - name: Push Base container 
#      run: docker push cwuensch/synobuild:base_${{ matrix.version }}

  docker:
    name: Platform container
    needs: base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [6.1, 6.2]
        platform: [rtd1296, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Build Platform container
      run: docker build --build-arg DSM_VERSION=${{ matrix.version }} --build-arg DSM_PLATFORM=${{ matrix.platform }} -t cwuensch/synobuild:${{ matrix.platform }}_${{ matrix.version }} .
      
#    - name: Push Platform container
#      run: docker push cwuensch/synobuild:${{ matrix.platform }}_${{ matrix.version }}

  combi:
    name: Combi container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [6.1, 6.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout toolkit repository
      uses: actions/checkout@v2
      with:
        repository: SynologyOpenSource/pkgscripts-ng
        ref: master
        path: pkgscripts-ng

    - name: Login to DockerHub
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Build Combi container
      run: docker build --file Dockerfile.combi --build-arg DSM_VERSION=${{ matrix.version }} -t cwuensch/synobuild:${{ matrix.version }} .
      
#    - name: Push Combi container
#      run: docker push cwuensch/synobuild:${{ matrix.version }}
